### PR TITLE
ARRISAPP-68 return hidden state for newer clients (#18)

### PR DESCRIPTION
**Pull request by margret-jaison-infosys**
* ARRISAPP-68 return hidden state for newer clients

* ARRISAPP-68 replace float client version with string

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Internal ticket created for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4664

**Comment by viveksinghnarwaria** [comment]
Hi @margret-jaison-infosys Please bring the changes to 24Q2_sprint branch.

**Comment by viveksinghnarwaria** [comment]
24Q2 Sprint : https://github.com/rdkcentral/xdialserver/pull/107
Please close this PR.

**Comment by margret-jaison-infosys** [comment]
@viveksinghnarwaria is anything is pending from my side

**Comment by margret-jaison-infosys** [comment]
Hi Vivek,

Is anything is pending for this pull request.

Thanking you,
Margret Jaison

**Pull request closed without merging**
